# Generated by Django 6.1.1 on 2026-10-07 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_App', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='board',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='reviewer',
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=250)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_related_name', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Board',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('REVIEW', 'rewiev'), ('INPROGRESS', 'in-progress'), ('TODO', 'to-do')], default='TODO', max_length=20)),
                ('priority', models.CharField(choices=[('MEDIUM', 'medium'), ('HIGH', 'high'), ('LOW', 'low')], default='LOW', max_length=10)),
                ('due_date', models.DateField()),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignee', to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_board', to='kanban_App.board')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_reviewer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_task', to='kanban_App.task')),
            ],
            options={
                'verbose_name': 'Comment',
            },
        ),
        migrations.DeleteModel(
            name='Boards',
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
