# Generated by Django 6.1.1 on 2026-10-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_App', '0002_remove_tasks_board_remove_tasks_assignee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='titel',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='titel',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('LOW', 'low'), ('HIGH', 'high'), ('MEDIUM', 'medium')], default='LOW', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'to-do'), ('INPROGRESS', 'in-progress'), ('REVIEW', 'rewiev')], default='TODO', max_length=20),
        ),
    ]
